export const FOCUS_INPUT = "FOCUS_INPUT";
export const BLUR_INPUT = "BLUR_INPUT";
export const KEYWORD_CHANGE = "KEYWORD_CHANGE";
export const ACTION_SEARCH = "ACTION_SEARCH";
export const SET_SUMMONER_BASICINFO = "SET_SUMMONER_BASICINFO";
export const SUMMONER_NOT_FOUND = "SUMMONER_NOT_FOUND";
export const REMOVE_LIST = "REMOVE_LIST";
export const ADD_FAVORITE = "ADD_FAVORITE";